# Generated by Django 4.2.2 on 2023-07-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_doctor_profile_pic'),
        ('account', '0002_account_password_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='selectdoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.doctor'),
        ),
    ]
