# Generated by Django 4.2.2 on 2023-06-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('availabledate', models.DateField()),
                ('availabletime', models.TimeField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/doctorPic/')),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
